# Generated by Django 2.2.7 on 2019-12-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imgdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('academy', models.CharField(max_length=300)),
                ('info', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('academy_title', models.CharField(max_length=300)),
                ('academy_num', models.CharField(max_length=300)),
                ('training_date', models.CharField(max_length=300)),
                ('pay', models.CharField(max_length=300)),
                ('training_wage', models.CharField(max_length=300)),
                ('people', models.CharField(max_length=300)),
                ('training_time', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='itess.Topic')),
            ],
        ),
    ]
