# Generated by Django 2.2.7 on 2019-12-13 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='zzim_user',
            field=models.ManyToManyField(related_name='zzim_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
